"""
Django settings for NiwaProject project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os, re, environ
from pathlib import Path
from django.core.validators import RegexValidator



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# kjbhvg




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7fmu@^)#2=@4w#6mpc3nh7!owl*t&i33b%&_80yr!=g05uf*)-'


'''
"ADMIN_ENABLED = True" varibale to Enable Django admin page both in Localhost and Nginx server(internet)  , 
"ADMIN_ENABLED = "False" variable to disable Django admin page  both in Localhost and Nginx server(internet)

If we want to edit the django admin page in localhost only (not in Nginx), 
set DEBUG = True
ADMIN_ENABLED = True and 
run "python manage.py runserver". We can access the django admin page only thru http://localhost:8000/admin/

If we want to edit the django admin page in Nginx), 
set either DEBUG = True or DEBUG = False
ADMIN_ENABLED = True and 
run "sudo systemctl restart gunicorn". We can access the django admin page thru http://localhost:8000/admin/ and https://test.niwe.res.in/admin
'''
# SECURITY WARNING: don't run with debug turned on in production!

# DEBUG =  False
DEBUG =  True
# This configuration will allow you to bypass the default Django error pages and show the custom error pages for 404, 500, etc.
  
ADMIN_ENABLED = True

ALLOWED_HOSTS = ['192.168.16.31','niwe.res.in','127.0.0.1','localhost']

# Validators

alphanumeric = RegexValidator(r'^(?!.*<.*?>)(?!.*\$\()(?!.*javascript:)(?!.*style\s*=)(?!.*<style>)[a-zA-Z0-9&,/\\()\-_.:\s\[\]\'\"]*$','Only Alphanumeric Characters are Allowed.')
only_numbers = RegexValidator(r'^[0-9]*$', 'Only Numbers are Allowed.') 


INSTALLED_APPS = [
     
    'axes',
    'preventconcurrentlogins',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tinymce',  
    'about_section',
    'Media_Section',
    'Depart_Section',
    'Document_Section',
    'Contact_Us',
    'Staff_Section',
    'Right_To_Information',
    'Career_Section',   
    'certification_services',
    'inspection_services',
    'search_form',
    'home_sections',
    'Tenders',
    'django_otp',  
    'django_otp.plugins.otp_totp',  
    'sslserver' 
]



AUTHENTICATION_BACKENDS = [   
    #'axes.backends.AxesBackend'
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',  
  
 ]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',   
    'django_otp.middleware.OTPMiddleware',   
    'axes.middleware.AxesMiddleware',
    'preventconcurrentlogins.middleware.PreventConcurrentLoginsMiddleware',
    'NiwaProject.middleware.AdminIdleTimeoutMiddleware',  # Add this for Django admin page session logout idle for 20 mins
    'NiwaProject.middleware.SessionSecurityMiddleware',  #Added this from preventing django session hijacking
    'NiwaProject.middleware.BlockBotsMiddleware',  #To block bot agent requests and blocked IP
    'NiwaProject.middleware.VisitorCounterMiddleware', # For visitor count

]

# CACHES = {
#      'default': {
#          'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#      },
#      'axes_cache': {
#          'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
#      }
#  }

# For login failed attempt

AXES_CACHE = 'axes_cache'
AXES_FAILURE_LIMIT = 5
AXES_LOCKOUT_PARAMETERS = ['username','ip_address']
AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = True
AXES_RESET_ON_SUCCESS  = False
AXES_COOLOFF_TIME = 1
AXES_LOCKOUT_TEMPLATE ='axes/lockout.html'
AXES_LOCKOUT_AT_FAILURE = True

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'file': {
#             'level': 'INFO',
#             'class': 'logging.FileHandler',
#             'filename': '/var/log/django/session_security.log',  # Change this path as needed
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['file'],
#             'level': 'INFO',
#             'propagate': True,
#         },
#     },
# }

ADMIN_SESSION_IDLE_TIMEOUT = 1200
ROOT_URLCONF = 'NiwaProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'NiwaProject.context_processors.footer_details',
            ],
        },
    },
]

WSGI_APPLICATION = 'NiwaProject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

env = environ.Env()
env.read_env()

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": 'niwe_project',
        "USER": "admin",
        "PASSWORD": "admin@04",
        "HOST": "127.0.0.1",
        "PORT": "5432",
    },
     
    
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
from django.utils.translation import gettext_lazy as _

LANGUAGE_CODE = 'en'

LANGUAGES = (
    ('en', 'English'),
    ('hi', 'Hindi'),
)

TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


#SESSION_EXPIRE_SECONDS = 300
SESSION_COOKIE_AGE = 1200
SESSION_COOKIE_SAMESITE = 'Strict'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SECURE_BROWSER_XSS_FILTER = True

SECURE_SSL_REDIRECT = True
# SECURE_HSTS_PRELOAD = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS= True

CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'Strict'
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True



SESSION_ENGINE = 'django.contrib.sessions.backends.db'
# SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
# SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Additional static files directory
]
STATIC_ROOT = '/var/www/static/'

# Media files (Uploaded files)
MEDIA_URL = '/media/'  # URL to access media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')  # Directory to store uploaded media files
# MEDIA_ROOT = '/var/www/media/'


# for file size
# DATA_UPLOAD_MAX_MEMORY_SIZE = 40485760  # 40 MB limit
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB limit



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TINYMCE_DEFAULT_CONFIG = {
    'height': 1000,
    'width': 1000,
    'content_style' : 'p {text-align : justify;}',
    'relative_urls' : False,
    'remote_script_host' : False,
    # 'document_base_url' : "https://niwe.res.in/",
    'document_base_url' : "https://127.0.0.1:8000/",
    'image_file_types' : 'png,jpg,jpeg,PNG,JPG,JPEG',
    'menubar': 'file edit view insert format tools table help',
    'plugins': 'advlist autolink lists link image charmap print preview anchor searchreplace visualblocks code fullscreen insertdatetime media table paste code help wordcount textcolor',  # Add textcolor plugin
    'toolbar': 'undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | forecolor backcolor',  # Add forecolor and backcolor to the toolbar
    
}






